### ISSUE TITLE
NullPointerException on pkManager.getKit().getOverlays() with no map configured

### ISSUE THREAD

**Issue by cupakromer** [RadiusNetworks/proximitykit-android#2]
If a Kit has no map configured, attempting to sync throws the dreaded `NullPointerException` :grimacing: 

```
11-13 11:24:27.554  25261-25319/com.radiusnetworks.androidproximitykitreference E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #2
    Process: com.radiusnetworks.androidproximitykitreference, PID: 25261
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:300)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.NullPointerException
            at com.radiusnetworks.proximity.model.Kit.getOverlays(SourceFile:47)
            at com.radiusnetworks.androidproximitykitreference.AndroidProximityKitReferenceApplication.didSync(AndroidProximityKitReferenceApplication.java:215)
            at com.radiusnetworks.proximity.ProximityKitManager$1.didSync(SourceFile:365)
            at com.radiusnetworks.proximity.beacon.data.proximitykit.ProximityKitPersister$1.requestComplete(SourceFile:66)
            at com.radiusnetworks.proximity.api.KitAsynchApi.doInBackground(SourceFile:30)
            at com.radiusnetworks.proximity.api.KitAsynchApi.doInBackground(SourceFile:12)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
```

### Steps to Reproduce:

1. Setup the [ProximityKit Reference](https://github.com/RadiusNetworks/proximitykit-reference-android)
2. Create a [new kit](https://proximitykit.radiusnetworks.com/kits/new) on [Proximity Kit](https://proximitykit.radiusnetworks.com) but do **not** set any beacons or maps.
3. Replace the reference applications `ProximityKit.properties` file with the newly created Kit.
4. Run the app :weary: 

### Workaround:

Create a map for the Kit but leave it empty.

**Comment by cupakromer** [comment]
This is now fixed in the latest release [0.3.0](https://github.com/RadiusNetworks/proximitykit-android/releases/tag/0.3.0)
